<?php

namespace App\Repository;

use App\Entity\Baby;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    /**
     * @param Baby $baby
     *
     * @return Query
     */
    public function findBabyProfilePicture(Baby $baby):Query
    {
        $query = $this->createQueryBuilder('photo')
            ->where('photo.baby = :baby')
            ->andWhere('photo.profilePicture = true')
            ->setParameter('baby', $baby);

        return $query->getQuery();

    }
}
