version: '2'
services:
  postgres:
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=root
      - PGADMIN_DEFAULT_PASSWORD=root
    depends_on:
      - postgres
  php:
    build: php-fpm
    ports:
      - '9002:9000'
    volumes:
      - ../:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/logs:cached
    links:
      - postgres
  nginx:
    build: nginx
    ports:
      - '8080:80'
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached
#  encore:
#    image: node:10-alpine
#    volumes:
#      -  ../:/var/www/symfony
#    ports:
#      - "8080:80"
#    working_dir: /var/www/symfony
#    command: ["yarn", "dev-server", "--host=0.0.0.0"]
volumes:
  postgres-data-volume:
    external: true